[package]
name = "audio_answers"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2 = "0.10.6"
clap = { version = "4.5.18", features = ["derive"] }
file-hashing = "0.1.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
skyscraper = "0.6.4"

